sudo: false
language: node_js
node_js:
  - "stable"
script: "./etc/build.sh"
env:
  global:
    secure: "eB7zHiBw+QMixVU6uehj5i9SwSSpRwhYnHvZnCBQQivDbgg8b6Sl4KD2GDaplFYpnog1W0sOzOB4+AvDqkjOg58+YgqE7NavGDYdSWqY9ExQeN3saBbpnc0/IcXVsAPCIe032obHdpb5BiAl0QJBiJZCI/gsz3w57GOvM4V0QAQ="
notifications:
  email: false
